# Generated by Django 3.0.7 on 2020-07-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters_api', '0003_auto_20200701_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='demo',
            field=models.CharField(default='https://cdn.fbsbx.com/v/t65.23977-21/105893505_877061342783340_7230112254744392680_n.mov?_nc_cat=102&_nc_sid=56eb5b&_nc_ohc=ERvjtiF3Qg4AX_bP06v&_nc_ht=cdn.fbsbx.com&oh=698744b3bb251ea7b5044ec5dc567a4b&oe=5EFF250B', max_length=400),
            preserve_default=False,
        ),
    ]
