# Generated by Django 3.0.7 on 2020-07-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters_api', '0004_auto_20200702_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='slug',
        ),
    ]
