# Generated by Django 3.0.7 on 2020-07-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters_api', '0005_remove_filter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='demo_replace',
            field=models.FileField(null=True, upload_to='./demo_replace/', verbose_name=''),
        ),
    ]
