# Generated by Django 3.0.7 on 2020-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters_api', '0006_filter_demo_replace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='demo_replace',
            field=models.FileField(null=True, upload_to='./demo_replace/'),
        ),
    ]
